### ISSUE TITLE
Un-gated RNN cannot compile

### ISSUE THREAD

**Issue by julianser** [sordonia/hed-dlg#9]
The method "plain_step(self, xd_t, m_t, hs_t, hd_tm1)" in dialog.encdec.py uses the variable Wd_s_q, but this variable Wd_s_q is only defined for the gated step. I am not sure how to solve the problem, but until we solve it we cannot run the simple (un-gated) RNN. @sordonia

**Comment by julianser** [comment]
A solution could be to replace this with Wd_s_0, but still the model cannot compile. At this point I get the error:

Traceback (most recent call last):
  File "train.py", line 281, in <module>
    main(args)
  File "train.py", line 190, in main
    c = train_batch(x_data, max_length, x_cost_mask)
  File "/u/serbaniv/Theano/Theano/theano/compile/function_module.py", line 606, in **call**
    storage_map=self.fn.storage_map)
  File "/u/serbaniv/Theano/Theano/theano/compile/function_module.py", line 595, in **call**
    outputs = self.fn()
ValueError: Input dimension mis-match. (input[0].shape[0] = 400, input[1].shape[0] = 520)
Apply node that caused the error: Elemwise{Composite{(log(i0) \* i1)}}(ExtractDiag{view=False}.0, Flatten{1}.0)
Inputs types: [TensorType(float32, vector), TensorType(float32, vector)]
Inputs shapes: [(400,), (520,)]
Inputs strides: [(4,), (4,)]
Inputs values: ['not shown', 'not shown']

**Comment by julianser** [comment]
The error must be in the encoder, because when I use gated connections only in the decoder everything works as it should.

**Comment by sordonia** [comment]
Ok i'll fix this, this should be simple.
